server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Sayyod
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
